language: elixir

matrix:
  include:
    - otp_release: 19.0
      elixir: 1.3.0
    - otp_release: 20.2
      elixir: 1.6.3

sudo: false

before_install:
  - curl https://sh.rustup.rs | sh -s -- -y
  - export PATH="$HOME/.cargo/bin:$PATH"