language: elixir

matrix:
  include:
    - otp_release: 20.0
      elixir: 1.6.0
    - otp_release: 20.0
      elixir: 1.9.0
    - otp_release: 21.0
      elixir: 1.6.6
    - otp_release: 21.0
      elixir: 1.10.0
    - otp_release: 22.0
      elixir: 1.7.0
    - otp_release: 22.0
      elixir: 1.10.0

sudo: false

before_install:
  - curl https://sh.rustup.rs | sh -s -- -y
  - export PATH="$HOME/.cargo/bin:$PATH"

cache:
  directories:
    - _build
    - deps
    - $HOME/.cargo